// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: desc.proto

package server

import (
	"context"

	"ovra/app/system/internal/logic/rolerpc"
	"ovra/app/system/internal/svc"
	"ovra/app/system/pb/system"
)

type RoleRpcServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedRoleRpcServer
}

func NewRoleRpcServer(svcCtx *svc.ServiceContext) *RoleRpcServer {
	return &RoleRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RoleRpcServer) Ping(ctx context.Context, in *system.Request) (*system.Response, error) {
	l := rolerpclogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
