// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportVisualMap = "report_visual_map"

// ReportVisualMap 可视化地图配置
type ReportVisualMap struct {
	UUID         string    `gorm:"column:uuid;primaryKey;comment:主键" json:"uuid"`                                 // 主键
	CreatorID    string    `gorm:"column:creator_id;comment:创建人id" json:"creator_id"`                             // 创建人id
	Creator      string    `gorm:"column:creator;comment:创建人" json:"creator"`                                     // 创建人
	CreateTime   time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建人姓名" json:"create_time"` // 创建人姓名
	ModifierID   string    `gorm:"column:modifier_id;comment:修改人id" json:"modifier_id"`                           // 修改人id
	Modifier     string    `gorm:"column:modifier;comment:修改人" json:"modifier"`                                   // 修改人
	ModifyTime   time.Time `gorm:"column:modify_time;comment:修改时间" json:"modify_time"`                            // 修改时间
	CreatorOrgID int32     `gorm:"column:creator_org_id;comment:创建人组织结构id" json:"creator_org_id"`                 // 创建人组织结构id
	TenantUUID   string    `gorm:"column:tenant_uuid;comment:租户UUID" json:"tenant_uuid"`                          // 租户UUID
	Name         string    `gorm:"column:name;comment:地图名称" json:"name"`                                          // 地图名称
	Data         string    `gorm:"column:data;comment:地图数据" json:"data"`                                          // 地图数据
	Remark       string    `gorm:"column:remark;comment:备注" json:"remark"`                                        // 备注
}

// TableName ReportVisualMap's table name
func (*ReportVisualMap) TableName() string {
	return TableNameReportVisualMap
}
