// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportDataReport = "report_data_report"

// ReportDataReport 数据报表管理表
type ReportDataReport struct {
	UUID                 string    `gorm:"column:uuid;primaryKey;comment:主键" json:"uuid"`                                 // 主键
	CreatorID            string    `gorm:"column:creator_id;comment:创建人Id" json:"creator_id"`                             // 创建人Id
	Creator              string    `gorm:"column:creator;comment:创建人" json:"creator"`                                     // 创建人
	CreateTime           time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`  // 创建时间
	ModifierID           string    `gorm:"column:modifier_id;comment:修改人Id" json:"modifier_id"`                           // 修改人Id
	Modifier             string    `gorm:"column:modifier;comment:修改人" json:"modifier"`                                   // 修改人
	ModifyTime           time.Time `gorm:"column:modify_time;comment:修改时间" json:"modify_time"`                            // 修改时间
	TenantUUID           string    `gorm:"column:tenant_uuid;comment:租户UUID" json:"tenant_uuid"`                          // 租户UUID
	DataReportName       string    `gorm:"column:data_report_name;comment:报表名称" json:"data_report_name"`                  // 报表名称
	DataReportContent    []byte    `gorm:"column:data_report_content;comment:报表流数据" json:"data_report_content"`           // 报表流数据
	DataReportContentXML string    `gorm:"column:data_report_content_xml;comment:报表xml数据" json:"data_report_content_xml"` // 报表xml数据
	CompanyID            int32     `gorm:"column:company_id;comment:公司Id" json:"company_id"`                              // 公司Id
	DataReportCode       string    `gorm:"column:data_report_code;comment:编码" json:"data_report_code"`                    // 编码
	DataReportType       string    `gorm:"column:data_report_type;comment:类型" json:"data_report_type"`                    // 类型
	DataReportSort       int32     `gorm:"column:data_report_sort;comment:排序" json:"data_report_sort"`                    // 排序
	DataReportDesc       string    `gorm:"column:data_report_desc;comment:描述" json:"data_report_desc"`                    // 描述
	CreatorOrgID         int32     `gorm:"column:creator_org_id;comment:创建人组织机构ID" json:"creator_org_id"`                 // 创建人组织机构ID
	DataReportStatus     string    `gorm:"column:data_report_status;comment:预留字段——状态(是否走回收站)" json:"data_report_status"`  // 预留字段——状态(是否走回收站)
	DataReportImg        string    `gorm:"column:data_report_img;comment:预留字段——报表背景" json:"data_report_img"`              // 预留字段——报表背景
}

// TableName ReportDataReport's table name
func (*ReportDataReport) TableName() string {
	return TableNameReportDataReport
}
