// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportVisualCategory = "report_visual_category"

// ReportVisualCategory 可视化分类表
type ReportVisualCategory struct {
	UUID          string    `gorm:"column:uuid;primaryKey;comment:主键" json:"uuid"`                                 // 主键
	CreatorID     string    `gorm:"column:creator_id;comment:创建人id" json:"creator_id"`                             // 创建人id
	Creator       string    `gorm:"column:creator;comment:创建人" json:"creator"`                                     // 创建人
	CreateTime    time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建人姓名" json:"create_time"` // 创建人姓名
	ModifierID    string    `gorm:"column:modifier_id;comment:修改人id" json:"modifier_id"`                           // 修改人id
	Modifier      string    `gorm:"column:modifier;comment:修改人" json:"modifier"`                                   // 修改人
	ModifyTime    time.Time `gorm:"column:modify_time;comment:修改时间" json:"modify_time"`                            // 修改时间
	CreatorOrgID  int32     `gorm:"column:creator_org_id;comment:创建人组织结构id" json:"creator_org_id"`                 // 创建人组织结构id
	TenantUUID    string    `gorm:"column:tenant_uuid;comment:租户UUID" json:"tenant_uuid"`                          // 租户UUID
	CategoryKey   string    `gorm:"column:category_key;comment:分类键值" json:"category_key"`                          // 分类键值
	CategoryValue string    `gorm:"column:category_value;comment:分类名称" json:"category_value"`                      // 分类名称
	IsDeleted     int32     `gorm:"column:is_deleted;comment:是否已删除" json:"is_deleted"`                             // 是否已删除
}

// TableName ReportVisualCategory's table name
func (*ReportVisualCategory) TableName() string {
	return TableNameReportVisualCategory
}
