// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportClassification = "report_classification"

// ReportClassification 数据报表分类
type ReportClassification struct {
	UUID                 string    `gorm:"column:uuid;primaryKey;comment:主键" json:"uuid"`                                // 主键
	CreatorID            string    `gorm:"column:creator_id;comment:创建人Id" json:"creator_id"`                            // 创建人Id
	Creator              string    `gorm:"column:creator;comment:创建人" json:"creator"`                                    // 创建人
	CreateTime           time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	ModifierID           string    `gorm:"column:modifier_id;comment:修改人Id" json:"modifier_id"`                          // 修改人Id
	Modifier             string    `gorm:"column:modifier;comment:修改人" json:"modifier"`                                  // 修改人
	ModifyTime           time.Time `gorm:"column:modify_time;comment:修改时间" json:"modify_time"`                           // 修改时间
	TenantUUID           string    `gorm:"column:tenant_uuid;comment:租户UUID" json:"tenant_uuid"`                         // 租户UUID
	CreatorOrgID         int32     `gorm:"column:creator_org_id;comment:创建人组织机构ID" json:"creator_org_id"`                // 创建人组织机构ID
	ClassificationName   string    `gorm:"column:classification_name;comment:分类名称" json:"classification_name"`           // 分类名称
	ClassificationCode   string    `gorm:"column:classification_code;comment:分类编码" json:"classification_code"`           // 分类编码
	ClassificationSort   int32     `gorm:"column:classification_sort;comment:排序" json:"classification_sort"`             // 排序
	ClassificationRemark string    `gorm:"column:classification_remark;comment:备注" json:"classification_remark"`         // 备注
}

// TableName ReportClassification's table name
func (*ReportClassification) TableName() string {
	return TableNameReportClassification
}
