// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportVisualDb = "report_visual_db"

// ReportVisualDb 可视化数据源配置表
type ReportVisualDb struct {
	UUID         string    `gorm:"column:uuid;primaryKey;comment:主键" json:"uuid"`                                 // 主键
	CreatorID    string    `gorm:"column:creator_id;comment:创建人id" json:"creator_id"`                             // 创建人id
	CreateTime   time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建人姓名" json:"create_time"` // 创建人姓名
	Creator      string    `gorm:"column:creator;comment:创建人" json:"creator"`                                     // 创建人
	ModifierID   string    `gorm:"column:modifier_id;comment:修改人id" json:"modifier_id"`                           // 修改人id
	Modifier     string    `gorm:"column:modifier;comment:修改人" json:"modifier"`                                   // 修改人
	ModifyTime   time.Time `gorm:"column:modify_time;comment:修改时间" json:"modify_time"`                            // 修改时间
	CreatorOrgID int32     `gorm:"column:creator_org_id;comment:创建人组织结构id" json:"creator_org_id"`                 // 创建人组织结构id
	TenantUUID   string    `gorm:"column:tenant_uuid;comment:租户UUID" json:"tenant_uuid"`                          // 租户UUID
	Name         string    `gorm:"column:name;comment:名称" json:"name"`                                            // 名称
	DriverClass  string    `gorm:"column:driver_class;comment:驱动类" json:"driver_class"`                           // 驱动类
	URL          string    `gorm:"column:url;comment:连接地址" json:"url"`                                            // 连接地址
	Username     string    `gorm:"column:username;comment:用户名" json:"username"`                                   // 用户名
	Password     string    `gorm:"column:password;comment:密码" json:"password"`                                    // 密码
	Remark       string    `gorm:"column:remark;comment:备注" json:"remark"`                                        // 备注
	Status       int32     `gorm:"column:status;comment:状态" json:"status"`                                        // 状态
	IsDeleted    int32     `gorm:"column:is_deleted;comment:是否已删除" json:"is_deleted"`                             // 是否已删除
}

// TableName ReportVisualDb's table name
func (*ReportVisualDb) TableName() string {
	return TableNameReportVisualDb
}
