// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportVisualRecord = "report_visual_record"

// ReportVisualRecord 可视化大屏数据集
type ReportVisualRecord struct {
	UUID          string    `gorm:"column:uuid;primaryKey;comment:主键" json:"uuid"`                                // 主键
	CreatorID     string    `gorm:"column:creator_id;comment:创建人id" json:"creator_id"`                            // 创建人id
	Creator       string    `gorm:"column:creator;comment:创建人" json:"creator"`                                    // 创建人
	CreateTime    time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	ModifierID    string    `gorm:"column:modifier_id;comment:修改人id" json:"modifier_id"`                          // 修改人id
	Modifier      string    `gorm:"column:modifier;comment:修改人" json:"modifier"`                                  // 修改人
	ModifyTime    time.Time `gorm:"column:modify_time;comment:修改时间" json:"modify_time"`                           // 修改时间
	CreatorOrgID  int32     `gorm:"column:creator_org_id;comment:创建人组织结构id" json:"creator_org_id"`                // 创建人组织结构id
	TenantUUID    string    `gorm:"column:tenant_uuid;comment:租户UUID" json:"tenant_uuid"`                         // 租户UUID
	ID            int32     `gorm:"column:id;comment:id" json:"id"`                                               // id
	Name          string    `gorm:"column:name;comment:名称" json:"name"`                                           // 名称
	URL           string    `gorm:"column:url;comment:地址" json:"url"`                                             // 地址
	DataType      int32     `gorm:"column:data_type;comment:请求类型" json:"data_type"`                               // 请求类型
	DataMethod    string    `gorm:"column:data_method;comment:请求方式" json:"data_method"`                           // 请求方式
	Data          string    `gorm:"column:data;comment:数据" json:"data"`                                           // 数据
	DataQuery     string    `gorm:"column:data_query;comment:请求查询数据" json:"data_query"`                           // 请求查询数据
	DataQueryType string    `gorm:"column:data_query_type;comment:查询类型" json:"data_query_type"`                   // 查询类型
	DataFormatter string    `gorm:"column:data_formatter;comment:数据格式化" json:"data_formatter"`                    // 数据格式化
	WsURL         string    `gorm:"column:ws_url;comment:websocket地址" json:"ws_url"`                              // websocket地址
	DataHeader    string    `gorm:"column:data_header;comment:请求头参数" json:"data_header"`                          // 请求头参数
	DbUUID        string    `gorm:"column:db_uuid;comment:数据库连接UUID" json:"db_uuid"`                              // 数据库连接UUID
	DbSql         string    `gorm:"column:db_sql;comment:SQL语句" json:"db_sql"`                                    // SQL语句
}

// TableName ReportVisualRecord's table name
func (*ReportVisualRecord) TableName() string {
	return TableNameReportVisualRecord
}
