// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportVisualConfig = "report_visual_config"

// ReportVisualConfig 可视化配置表
type ReportVisualConfig struct {
	UUID         string    `gorm:"column:uuid;primaryKey;comment:主键" json:"uuid"`                                 // 主键
	VisualID     string    `gorm:"column:visual_id;comment:可视化表主键" json:"visual_id"`                              // 可视化表主键
	CreatorID    string    `gorm:"column:creator_id;comment:创建人id" json:"creator_id"`                             // 创建人id
	Creator      string    `gorm:"column:creator;comment:创建人" json:"creator"`                                     // 创建人
	CreateTime   time.Time `gorm:"column:create_time;default:CURRENT_TIMESTAMP;comment:创建人姓名" json:"create_time"` // 创建人姓名
	ModifierID   string    `gorm:"column:modifier_id;comment:修改人id" json:"modifier_id"`                           // 修改人id
	Modifier     string    `gorm:"column:modifier;comment:修改人" json:"modifier"`                                   // 修改人
	ModifyTime   time.Time `gorm:"column:modify_time;comment:修改时间" json:"modify_time"`                            // 修改时间
	CreatorOrgID int32     `gorm:"column:creator_org_id;comment:创建人组织结构id" json:"creator_org_id"`                 // 创建人组织结构id
	TenantUUID   string    `gorm:"column:tenant_uuid;comment:租户UUID" json:"tenant_uuid"`                          // 租户UUID
	Component    string    `gorm:"column:component;comment:组件json" json:"component"`                              // 组件json
	Detail       string    `gorm:"column:detail;comment:配置json" json:"detail"`                                    // 配置json
}

// TableName ReportVisualConfig's table name
func (*ReportVisualConfig) TableName() string {
	return TableNameReportVisualConfig
}
