// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportVisual = "report_visual"

// ReportVisual 可视化主表表
type ReportVisual struct {
	UUID          string    `gorm:"column:uuid;primaryKey;comment:主键" json:"uuid"`                 // 主键
	Title         string    `gorm:"column:title;comment:大屏标题" json:"title"`                        // 大屏标题
	BackgroundURL string    `gorm:"column:background_url;comment:大屏背景" json:"background_url"`      // 大屏背景
	Category      string    `gorm:"column:category;comment:大屏类型" json:"category"`                  // 大屏类型
	Password      string    `gorm:"column:password;comment:发布密码" json:"password"`                  // 发布密码
	CreateUser    int64     `gorm:"column:create_user;comment:创建人" json:"create_user"`             // 创建人
	CreateDept    int64     `gorm:"column:create_dept;comment:创建部门" json:"create_dept"`            // 创建部门
	CreateTime    time.Time `gorm:"column:create_time;comment:创建时间" json:"create_time"`            // 创建时间
	UpdateUser    int64     `gorm:"column:update_user;comment:修改人" json:"update_user"`             // 修改人
	UpdateTime    time.Time `gorm:"column:update_time;comment:修改时间" json:"update_time"`            // 修改时间
	Status        int32     `gorm:"column:status;comment:状态" json:"status"`                        // 状态
	IsDeleted     int32     `gorm:"column:is_deleted;comment:是否已删除" json:"is_deleted"`             // 是否已删除
	CreatorID     string    `gorm:"column:creator_id;comment:创建人ID" json:"creator_id"`             // 创建人ID
	Creator       string    `gorm:"column:creator;comment:创建人" json:"creator"`                     // 创建人
	ModifierID    string    `gorm:"column:modifier_id;comment:修改人Id" json:"modifier_id"`           // 修改人Id
	Modifier      string    `gorm:"column:modifier;comment:修改人" json:"modifier"`                   // 修改人
	ModifyTime    time.Time `gorm:"column:modify_time;comment:修改时间" json:"modify_time"`            // 修改时间
	CreatorOrgID  int32     `gorm:"column:creator_org_id;comment:创建人组织机构ID" json:"creator_org_id"` // 创建人组织机构ID
	TenantUUID    string    `gorm:"column:tenant_uuid;comment:租户UUID" json:"tenant_uuid"`          // 租户UUID
}

// TableName ReportVisual's table name
func (*ReportVisual) TableName() string {
	return TableNameReportVisual
}
