// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: desc.proto

package server

import (
	"context"

	"ovra/app/monitor/internal/logic/logininforpc"
	"ovra/app/monitor/internal/svc"
	"ovra/app/monitor/pb/monitor"
)

type LoginInfoRpcServer struct {
	svcCtx *svc.ServiceContext
	monitor.UnimplementedLoginInfoRpcServer
}

func NewLoginInfoRpcServer(svcCtx *svc.ServiceContext) *LoginInfoRpcServer {
	return &LoginInfoRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginInfoRpcServer) Save(ctx context.Context, in *monitor.LoginInfoReq) (*monitor.EmptyResp, error) {
	l := logininforpclogic.NewSaveLogic(ctx, s.svcCtx)
	return l.Save(in)
}
