// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: desc.proto

package userrpc

import (
	"context"

	"ovra/app/system/pb/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = system.Request
	Response = system.Response

	UserRpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultUserRpc struct {
		cli zrpc.Client
	}
)

func NewUserRpc(cli zrpc.Client) UserRpc {
	return &defaultUserRpc{
		cli: cli,
	}
}

func (m *defaultUserRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := system.NewUserRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
