// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CaptchaResp struct {
	CaptchaEnabled bool   `json:"captchaEnabled"`
	Img            string `json:"img"`
	Uuid           string `json:"uuid"`
}

type LoginReq struct {
	Username  string `json:"username"`
	Password  string `json:"password"`
	ClientId  string `json:"clientId"`
	TenantId  string `json:"tenantId"`
	GrantType string `json:"grantType"`
	Code      string `json:"code,optional"`
	Uuid      string `json:"uuid,optional"`
}

type LoginResp struct {
	AccessToken     string `json:"access_token"`
	RefreshToken    string `json:"refresh_token"`
	ClientId        string `json:"client_id"`
	ExpireIn        int64  `json:"expire_in"`
	RefreshExpireIn int64  `json:"refresh_expire_in"`
}

type TenantResp struct {
	TenantEnabled bool       `json:"tenantEnabled"`
	VoList        []TenantVo `json:"voList"`
}

type TenantVo struct {
	TenantId    string `json:"tenantId"`
	CompanyName string `json:"companyName"`
	Domain      string `json:"domain"`
}
