// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: desc.proto

package rolerpc

import (
	"context"

	"ovra/app/system/pb/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = system.Request
	Response = system.Response

	RoleRpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultRoleRpc struct {
		cli zrpc.Client
	}
)

func NewRoleRpc(cli zrpc.Client) RoleRpc {
	return &defaultRoleRpc{
		cli: cli,
	}
}

func (m *defaultRoleRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := system.NewRoleRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
