// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ChangeStatusOssConfigReq struct {
	OssConfigId string `json:"ossConfigId"`
	ConfigKey   string `json:"configKey"`
	Status      string `json:"status"`
}

type IdReq struct {
	Id string `path:"id"`
}

type IdsReq struct {
	Ids string `path:"ids"`
}

type ModifyOssConfigReq struct {
	OssConfigBase
}

type ModifyOssReq struct {
	OssBase
}

type OssBase struct {
	OssId        string `json:"ossId,optional"`        // 对象存储主键
	TenantId     string `json:"tenantId,optional"`     // 租户编号
	FileName     string `json:"fileName,optional"`     // 文件名
	OriginalName string `json:"originalName,optional"` // 原名
	FileSuffix   string `json:"fileSuffix,optional"`   // 文件后缀名
	Url          string `json:"url,optional"`          // URL地址
	Ext1         string `json:"ext1,optional"`         // 扩展字段
	CreateDept   int64  `json:"createDept,optional"`   // 创建部门
	CreateTime   string `json:"createTime,optional"`   // 创建时间
	CreateBy     int64  `json:"createBy,optional"`     // 上传人
	UpdateTime   string `json:"updateTime,optional"`   // 更新时间
	UpdateBy     int64  `json:"updateBy,optional"`     // 更新人
	Service      string `json:"service,optional"`      // 服务商
}

type OssConfigBase struct {
	OssConfigID  string `json:"ossConfigId,optional"`  // 主键
	TenantId     string `json:"tenantId,optional"`     // 租户编号
	ConfigKey    string `json:"configKey,optional"`    // 配置key
	AccessKey    string `json:"accessKey,optional"`    // accessKey
	SecretKey    string `json:"secretKey,optional"`    // 秘钥
	BucketName   string `json:"bucketName,optional"`   // 桶名称
	Prefix       string `json:"prefix,optional"`       // 前缀
	Endpoint     string `json:"endpoint,optional"`     // 访问站点
	Domain       string `json:"domain,optional"`       // 自定义域名
	IsHTTPS      string `json:"isHttps,optional"`      // 是否https（Y=是,N=否）
	Region       string `json:"region,optional"`       // 域
	AccessPolicy string `json:"accessPolicy,optional"` // 桶权限类型(0=private 1=public 2=custom)
	Status       string `json:"status,optional"`       // 是否默认（0=是,1=否）
	Ext1         string `json:"ext1,optional"`         // 扩展字段
	CreateDept   int64  `json:"createDept,optional"`   // 创建部门
	CreateBy     int64  `json:"createBy,optional"`     // 创建者
	CreateTime   string `json:"createTime,optional"`   // 创建时间
	UpdateBy     int64  `json:"updateBy,optional"`     // 更新者
	UpdateTime   string `json:"updateTime,optional"`   // 更新时间
	Remark       string `json:"remark,optional"`       // 备注
}

type OssConfigQuery struct {
	OssConfigID  string `form:"ossConfigId,optional"`  // 主键
	TenantId     string `form:"tenantId,optional"`     // 租户编号
	ConfigKey    string `form:"configKey,optional"`    // 配置key
	AccessKey    string `form:"accessKey,optional"`    // accessKey
	SecretKey    string `form:"secretKey,optional"`    // 秘钥
	BucketName   string `form:"bucketName,optional"`   // 桶名称
	Prefix       string `form:"prefix,optional"`       // 前缀
	Endpoint     string `form:"endpoint,optional"`     // 访问站点
	Domain       string `form:"domain,optional"`       // 自定义域名
	IsHTTPS      string `form:"isHttps,optional"`      // 是否https（Y=是,N=否）
	Region       string `form:"region,optional"`       // 域
	AccessPolicy string `form:"accessPolicy,optional"` // 桶权限类型(0=private 1=public 2=custom)
	Status       string `form:"status,optional"`       // 是否默认（0=是,1=否）
	Ext1         string `form:"ext1,optional"`         // 扩展字段
	CreateDept   int64  `form:"createDept,optional"`   // 创建部门
	CreateBy     int64  `form:"createBy,optional"`     // 创建者
	CreateTime   string `form:"createTime,optional"`   // 创建时间
	UpdateBy     int64  `form:"updateBy,optional"`     // 更新者
	UpdateTime   string `form:"updateTime,optional"`   // 更新时间
	Remark       string `form:"remark,optional"`       // 备注
}

type OssQuery struct {
	OssId        string `form:"ossId,optional"`        // 对象存储主键
	TenantId     string `form:"tenantId,optional"`     // 租户编号
	FileName     string `form:"fileName,optional"`     // 文件名
	OriginalName string `form:"originalName,optional"` // 原名
	FileSuffix   string `form:"fileSuffix,optional"`   // 文件后缀名
	Url          string `form:"url,optional"`          // URL地址
	Ext1         string `form:"ext1,optional"`         // 扩展字段
	CreateDept   int64  `form:"createDept,optional"`   // 创建部门
	CreateTime   string `form:"createTime,optional"`   // 创建时间
	CreateBy     int64  `form:"createBy,optional"`     // 上传人
	UpdateTime   string `form:"updateTime,optional"`   // 更新时间
	UpdateBy     int64  `form:"updateBy,optional"`     // 更新人
	Service      string `form:"service,optional"`      // 服务商
}

type PageReq struct {
	PageNum  int64 `form:"pageNum,default=1"`
	PageSize int64 `form:"pageSize,default=20"`
	TimeReq
}

type PageSetOssConfigReq struct {
	PageReq
	OssConfigQuery
}

type PageSetOssConfigResp struct {
	Rows  []*OssConfigBase `json:"rows"`
	Total int64            `json:"total"`
}

type PageSetOssReq struct {
	PageReq
	OssQuery
}

type PageSetOssResp struct {
	Rows  []*OssBase `json:"rows"`
	Total int64      `json:"total"`
}

type TimeReq struct {
	BeginTime string `form:"params[beginTime],optional"`
	EndTime   string `form:"params[endTime],optional"`
}
