// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"report/internal/dal/model"
)

func newReportVisualConfig(db *gorm.DB, opts ...gen.DOOption) reportVisualConfig {
	_reportVisualConfig := reportVisualConfig{}

	_reportVisualConfig.reportVisualConfigDo.UseDB(db, opts...)
	_reportVisualConfig.reportVisualConfigDo.UseModel(&model.ReportVisualConfig{})

	tableName := _reportVisualConfig.reportVisualConfigDo.TableName()
	_reportVisualConfig.ALL = field.NewAsterisk(tableName)
	_reportVisualConfig.UUID = field.NewString(tableName, "uuid")
	_reportVisualConfig.VisualID = field.NewString(tableName, "visual_id")
	_reportVisualConfig.CreatorID = field.NewString(tableName, "creator_id")
	_reportVisualConfig.Creator = field.NewString(tableName, "creator")
	_reportVisualConfig.CreateTime = field.NewTime(tableName, "create_time")
	_reportVisualConfig.ModifierID = field.NewString(tableName, "modifier_id")
	_reportVisualConfig.Modifier = field.NewString(tableName, "modifier")
	_reportVisualConfig.ModifyTime = field.NewTime(tableName, "modify_time")
	_reportVisualConfig.CreatorOrgID = field.NewInt32(tableName, "creator_org_id")
	_reportVisualConfig.TenantUUID = field.NewString(tableName, "tenant_uuid")
	_reportVisualConfig.Component = field.NewString(tableName, "component")
	_reportVisualConfig.Detail = field.NewString(tableName, "detail")

	_reportVisualConfig.fillFieldMap()

	return _reportVisualConfig
}

// reportVisualConfig 可视化配置表
type reportVisualConfig struct {
	reportVisualConfigDo reportVisualConfigDo

	ALL          field.Asterisk
	UUID         field.String // 主键
	VisualID     field.String // 可视化表主键
	CreatorID    field.String // 创建人id
	Creator      field.String // 创建人
	CreateTime   field.Time   // 创建人姓名
	ModifierID   field.String // 修改人id
	Modifier     field.String // 修改人
	ModifyTime   field.Time   // 修改时间
	CreatorOrgID field.Int32  // 创建人组织结构id
	TenantUUID   field.String // 租户UUID
	Component    field.String // 组件json
	Detail       field.String // 配置json

	fieldMap map[string]field.Expr
}

func (r reportVisualConfig) Table(newTableName string) *reportVisualConfig {
	r.reportVisualConfigDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reportVisualConfig) As(alias string) *reportVisualConfig {
	r.reportVisualConfigDo.DO = *(r.reportVisualConfigDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reportVisualConfig) updateTableName(table string) *reportVisualConfig {
	r.ALL = field.NewAsterisk(table)
	r.UUID = field.NewString(table, "uuid")
	r.VisualID = field.NewString(table, "visual_id")
	r.CreatorID = field.NewString(table, "creator_id")
	r.Creator = field.NewString(table, "creator")
	r.CreateTime = field.NewTime(table, "create_time")
	r.ModifierID = field.NewString(table, "modifier_id")
	r.Modifier = field.NewString(table, "modifier")
	r.ModifyTime = field.NewTime(table, "modify_time")
	r.CreatorOrgID = field.NewInt32(table, "creator_org_id")
	r.TenantUUID = field.NewString(table, "tenant_uuid")
	r.Component = field.NewString(table, "component")
	r.Detail = field.NewString(table, "detail")

	r.fillFieldMap()

	return r
}

func (r *reportVisualConfig) WithContext(ctx context.Context) *reportVisualConfigDo {
	return r.reportVisualConfigDo.WithContext(ctx)
}

func (r reportVisualConfig) TableName() string { return r.reportVisualConfigDo.TableName() }

func (r reportVisualConfig) Alias() string { return r.reportVisualConfigDo.Alias() }

func (r reportVisualConfig) Columns(cols ...field.Expr) gen.Columns {
	return r.reportVisualConfigDo.Columns(cols...)
}

func (r *reportVisualConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reportVisualConfig) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 12)
	r.fieldMap["uuid"] = r.UUID
	r.fieldMap["visual_id"] = r.VisualID
	r.fieldMap["creator_id"] = r.CreatorID
	r.fieldMap["creator"] = r.Creator
	r.fieldMap["create_time"] = r.CreateTime
	r.fieldMap["modifier_id"] = r.ModifierID
	r.fieldMap["modifier"] = r.Modifier
	r.fieldMap["modify_time"] = r.ModifyTime
	r.fieldMap["creator_org_id"] = r.CreatorOrgID
	r.fieldMap["tenant_uuid"] = r.TenantUUID
	r.fieldMap["component"] = r.Component
	r.fieldMap["detail"] = r.Detail
}

func (r reportVisualConfig) clone(db *gorm.DB) reportVisualConfig {
	r.reportVisualConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r reportVisualConfig) replaceDB(db *gorm.DB) reportVisualConfig {
	r.reportVisualConfigDo.ReplaceDB(db)
	return r
}

type reportVisualConfigDo struct{ gen.DO }

func (r reportVisualConfigDo) Debug() *reportVisualConfigDo {
	return r.withDO(r.DO.Debug())
}

func (r reportVisualConfigDo) WithContext(ctx context.Context) *reportVisualConfigDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reportVisualConfigDo) ReadDB() *reportVisualConfigDo {
	return r.Clauses(dbresolver.Read)
}

func (r reportVisualConfigDo) WriteDB() *reportVisualConfigDo {
	return r.Clauses(dbresolver.Write)
}

func (r reportVisualConfigDo) Session(config *gorm.Session) *reportVisualConfigDo {
	return r.withDO(r.DO.Session(config))
}

func (r reportVisualConfigDo) Clauses(conds ...clause.Expression) *reportVisualConfigDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reportVisualConfigDo) Returning(value interface{}, columns ...string) *reportVisualConfigDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reportVisualConfigDo) Not(conds ...gen.Condition) *reportVisualConfigDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reportVisualConfigDo) Or(conds ...gen.Condition) *reportVisualConfigDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reportVisualConfigDo) Select(conds ...field.Expr) *reportVisualConfigDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reportVisualConfigDo) Where(conds ...gen.Condition) *reportVisualConfigDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reportVisualConfigDo) Order(conds ...field.Expr) *reportVisualConfigDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reportVisualConfigDo) Distinct(cols ...field.Expr) *reportVisualConfigDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reportVisualConfigDo) Omit(cols ...field.Expr) *reportVisualConfigDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reportVisualConfigDo) Join(table schema.Tabler, on ...field.Expr) *reportVisualConfigDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reportVisualConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) *reportVisualConfigDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reportVisualConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) *reportVisualConfigDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reportVisualConfigDo) Group(cols ...field.Expr) *reportVisualConfigDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reportVisualConfigDo) Having(conds ...gen.Condition) *reportVisualConfigDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reportVisualConfigDo) Limit(limit int) *reportVisualConfigDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reportVisualConfigDo) Offset(offset int) *reportVisualConfigDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reportVisualConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *reportVisualConfigDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reportVisualConfigDo) Unscoped() *reportVisualConfigDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reportVisualConfigDo) Create(values ...*model.ReportVisualConfig) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reportVisualConfigDo) CreateInBatches(values []*model.ReportVisualConfig, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reportVisualConfigDo) Save(values ...*model.ReportVisualConfig) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reportVisualConfigDo) First() (*model.ReportVisualConfig, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualConfig), nil
	}
}

func (r reportVisualConfigDo) Take() (*model.ReportVisualConfig, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualConfig), nil
	}
}

func (r reportVisualConfigDo) Last() (*model.ReportVisualConfig, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualConfig), nil
	}
}

func (r reportVisualConfigDo) Find() ([]*model.ReportVisualConfig, error) {
	result, err := r.DO.Find()
	return result.([]*model.ReportVisualConfig), err
}

func (r reportVisualConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ReportVisualConfig, err error) {
	buf := make([]*model.ReportVisualConfig, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reportVisualConfigDo) FindInBatches(result *[]*model.ReportVisualConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reportVisualConfigDo) Attrs(attrs ...field.AssignExpr) *reportVisualConfigDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reportVisualConfigDo) Assign(attrs ...field.AssignExpr) *reportVisualConfigDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reportVisualConfigDo) Joins(fields ...field.RelationField) *reportVisualConfigDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reportVisualConfigDo) Preload(fields ...field.RelationField) *reportVisualConfigDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reportVisualConfigDo) FirstOrInit() (*model.ReportVisualConfig, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualConfig), nil
	}
}

func (r reportVisualConfigDo) FirstOrCreate() (*model.ReportVisualConfig, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualConfig), nil
	}
}

func (r reportVisualConfigDo) FindByPage(offset int, limit int) (result []*model.ReportVisualConfig, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reportVisualConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reportVisualConfigDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reportVisualConfigDo) Delete(models ...*model.ReportVisualConfig) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reportVisualConfigDo) withDO(do gen.Dao) *reportVisualConfigDo {
	r.DO = *do.(*gen.DO)
	return r
}
