// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"report/internal/dal/model"
)

func newReportVisualCategory(db *gorm.DB, opts ...gen.DOOption) reportVisualCategory {
	_reportVisualCategory := reportVisualCategory{}

	_reportVisualCategory.reportVisualCategoryDo.UseDB(db, opts...)
	_reportVisualCategory.reportVisualCategoryDo.UseModel(&model.ReportVisualCategory{})

	tableName := _reportVisualCategory.reportVisualCategoryDo.TableName()
	_reportVisualCategory.ALL = field.NewAsterisk(tableName)
	_reportVisualCategory.UUID = field.NewString(tableName, "uuid")
	_reportVisualCategory.CreatorID = field.NewString(tableName, "creator_id")
	_reportVisualCategory.Creator = field.NewString(tableName, "creator")
	_reportVisualCategory.CreateTime = field.NewTime(tableName, "create_time")
	_reportVisualCategory.ModifierID = field.NewString(tableName, "modifier_id")
	_reportVisualCategory.Modifier = field.NewString(tableName, "modifier")
	_reportVisualCategory.ModifyTime = field.NewTime(tableName, "modify_time")
	_reportVisualCategory.CreatorOrgID = field.NewInt32(tableName, "creator_org_id")
	_reportVisualCategory.TenantUUID = field.NewString(tableName, "tenant_uuid")
	_reportVisualCategory.CategoryKey = field.NewString(tableName, "category_key")
	_reportVisualCategory.CategoryValue = field.NewString(tableName, "category_value")
	_reportVisualCategory.IsDeleted = field.NewInt32(tableName, "is_deleted")

	_reportVisualCategory.fillFieldMap()

	return _reportVisualCategory
}

// reportVisualCategory 可视化分类表
type reportVisualCategory struct {
	reportVisualCategoryDo reportVisualCategoryDo

	ALL           field.Asterisk
	UUID          field.String // 主键
	CreatorID     field.String // 创建人id
	Creator       field.String // 创建人
	CreateTime    field.Time   // 创建人姓名
	ModifierID    field.String // 修改人id
	Modifier      field.String // 修改人
	ModifyTime    field.Time   // 修改时间
	CreatorOrgID  field.Int32  // 创建人组织结构id
	TenantUUID    field.String // 租户UUID
	CategoryKey   field.String // 分类键值
	CategoryValue field.String // 分类名称
	IsDeleted     field.Int32  // 是否已删除

	fieldMap map[string]field.Expr
}

func (r reportVisualCategory) Table(newTableName string) *reportVisualCategory {
	r.reportVisualCategoryDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reportVisualCategory) As(alias string) *reportVisualCategory {
	r.reportVisualCategoryDo.DO = *(r.reportVisualCategoryDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reportVisualCategory) updateTableName(table string) *reportVisualCategory {
	r.ALL = field.NewAsterisk(table)
	r.UUID = field.NewString(table, "uuid")
	r.CreatorID = field.NewString(table, "creator_id")
	r.Creator = field.NewString(table, "creator")
	r.CreateTime = field.NewTime(table, "create_time")
	r.ModifierID = field.NewString(table, "modifier_id")
	r.Modifier = field.NewString(table, "modifier")
	r.ModifyTime = field.NewTime(table, "modify_time")
	r.CreatorOrgID = field.NewInt32(table, "creator_org_id")
	r.TenantUUID = field.NewString(table, "tenant_uuid")
	r.CategoryKey = field.NewString(table, "category_key")
	r.CategoryValue = field.NewString(table, "category_value")
	r.IsDeleted = field.NewInt32(table, "is_deleted")

	r.fillFieldMap()

	return r
}

func (r *reportVisualCategory) WithContext(ctx context.Context) *reportVisualCategoryDo {
	return r.reportVisualCategoryDo.WithContext(ctx)
}

func (r reportVisualCategory) TableName() string { return r.reportVisualCategoryDo.TableName() }

func (r reportVisualCategory) Alias() string { return r.reportVisualCategoryDo.Alias() }

func (r reportVisualCategory) Columns(cols ...field.Expr) gen.Columns {
	return r.reportVisualCategoryDo.Columns(cols...)
}

func (r *reportVisualCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reportVisualCategory) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 12)
	r.fieldMap["uuid"] = r.UUID
	r.fieldMap["creator_id"] = r.CreatorID
	r.fieldMap["creator"] = r.Creator
	r.fieldMap["create_time"] = r.CreateTime
	r.fieldMap["modifier_id"] = r.ModifierID
	r.fieldMap["modifier"] = r.Modifier
	r.fieldMap["modify_time"] = r.ModifyTime
	r.fieldMap["creator_org_id"] = r.CreatorOrgID
	r.fieldMap["tenant_uuid"] = r.TenantUUID
	r.fieldMap["category_key"] = r.CategoryKey
	r.fieldMap["category_value"] = r.CategoryValue
	r.fieldMap["is_deleted"] = r.IsDeleted
}

func (r reportVisualCategory) clone(db *gorm.DB) reportVisualCategory {
	r.reportVisualCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r reportVisualCategory) replaceDB(db *gorm.DB) reportVisualCategory {
	r.reportVisualCategoryDo.ReplaceDB(db)
	return r
}

type reportVisualCategoryDo struct{ gen.DO }

func (r reportVisualCategoryDo) Debug() *reportVisualCategoryDo {
	return r.withDO(r.DO.Debug())
}

func (r reportVisualCategoryDo) WithContext(ctx context.Context) *reportVisualCategoryDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reportVisualCategoryDo) ReadDB() *reportVisualCategoryDo {
	return r.Clauses(dbresolver.Read)
}

func (r reportVisualCategoryDo) WriteDB() *reportVisualCategoryDo {
	return r.Clauses(dbresolver.Write)
}

func (r reportVisualCategoryDo) Session(config *gorm.Session) *reportVisualCategoryDo {
	return r.withDO(r.DO.Session(config))
}

func (r reportVisualCategoryDo) Clauses(conds ...clause.Expression) *reportVisualCategoryDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reportVisualCategoryDo) Returning(value interface{}, columns ...string) *reportVisualCategoryDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reportVisualCategoryDo) Not(conds ...gen.Condition) *reportVisualCategoryDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reportVisualCategoryDo) Or(conds ...gen.Condition) *reportVisualCategoryDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reportVisualCategoryDo) Select(conds ...field.Expr) *reportVisualCategoryDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reportVisualCategoryDo) Where(conds ...gen.Condition) *reportVisualCategoryDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reportVisualCategoryDo) Order(conds ...field.Expr) *reportVisualCategoryDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reportVisualCategoryDo) Distinct(cols ...field.Expr) *reportVisualCategoryDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reportVisualCategoryDo) Omit(cols ...field.Expr) *reportVisualCategoryDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reportVisualCategoryDo) Join(table schema.Tabler, on ...field.Expr) *reportVisualCategoryDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reportVisualCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) *reportVisualCategoryDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reportVisualCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) *reportVisualCategoryDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reportVisualCategoryDo) Group(cols ...field.Expr) *reportVisualCategoryDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reportVisualCategoryDo) Having(conds ...gen.Condition) *reportVisualCategoryDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reportVisualCategoryDo) Limit(limit int) *reportVisualCategoryDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reportVisualCategoryDo) Offset(offset int) *reportVisualCategoryDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reportVisualCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *reportVisualCategoryDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reportVisualCategoryDo) Unscoped() *reportVisualCategoryDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reportVisualCategoryDo) Create(values ...*model.ReportVisualCategory) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reportVisualCategoryDo) CreateInBatches(values []*model.ReportVisualCategory, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reportVisualCategoryDo) Save(values ...*model.ReportVisualCategory) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reportVisualCategoryDo) First() (*model.ReportVisualCategory, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualCategory), nil
	}
}

func (r reportVisualCategoryDo) Take() (*model.ReportVisualCategory, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualCategory), nil
	}
}

func (r reportVisualCategoryDo) Last() (*model.ReportVisualCategory, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualCategory), nil
	}
}

func (r reportVisualCategoryDo) Find() ([]*model.ReportVisualCategory, error) {
	result, err := r.DO.Find()
	return result.([]*model.ReportVisualCategory), err
}

func (r reportVisualCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ReportVisualCategory, err error) {
	buf := make([]*model.ReportVisualCategory, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reportVisualCategoryDo) FindInBatches(result *[]*model.ReportVisualCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reportVisualCategoryDo) Attrs(attrs ...field.AssignExpr) *reportVisualCategoryDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reportVisualCategoryDo) Assign(attrs ...field.AssignExpr) *reportVisualCategoryDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reportVisualCategoryDo) Joins(fields ...field.RelationField) *reportVisualCategoryDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reportVisualCategoryDo) Preload(fields ...field.RelationField) *reportVisualCategoryDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reportVisualCategoryDo) FirstOrInit() (*model.ReportVisualCategory, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualCategory), nil
	}
}

func (r reportVisualCategoryDo) FirstOrCreate() (*model.ReportVisualCategory, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualCategory), nil
	}
}

func (r reportVisualCategoryDo) FindByPage(offset int, limit int) (result []*model.ReportVisualCategory, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reportVisualCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reportVisualCategoryDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reportVisualCategoryDo) Delete(models ...*model.ReportVisualCategory) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reportVisualCategoryDo) withDO(do gen.Dao) *reportVisualCategoryDo {
	r.DO = *do.(*gen.DO)
	return r
}
