// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"report/internal/dal/model"
)

func newReportVisualMap(db *gorm.DB, opts ...gen.DOOption) reportVisualMap {
	_reportVisualMap := reportVisualMap{}

	_reportVisualMap.reportVisualMapDo.UseDB(db, opts...)
	_reportVisualMap.reportVisualMapDo.UseModel(&model.ReportVisualMap{})

	tableName := _reportVisualMap.reportVisualMapDo.TableName()
	_reportVisualMap.ALL = field.NewAsterisk(tableName)
	_reportVisualMap.UUID = field.NewString(tableName, "uuid")
	_reportVisualMap.CreatorID = field.NewString(tableName, "creator_id")
	_reportVisualMap.Creator = field.NewString(tableName, "creator")
	_reportVisualMap.CreateTime = field.NewTime(tableName, "create_time")
	_reportVisualMap.ModifierID = field.NewString(tableName, "modifier_id")
	_reportVisualMap.Modifier = field.NewString(tableName, "modifier")
	_reportVisualMap.ModifyTime = field.NewTime(tableName, "modify_time")
	_reportVisualMap.CreatorOrgID = field.NewInt32(tableName, "creator_org_id")
	_reportVisualMap.TenantUUID = field.NewString(tableName, "tenant_uuid")
	_reportVisualMap.Name = field.NewString(tableName, "name")
	_reportVisualMap.Data = field.NewString(tableName, "data")
	_reportVisualMap.Remark = field.NewString(tableName, "remark")

	_reportVisualMap.fillFieldMap()

	return _reportVisualMap
}

// reportVisualMap 可视化地图配置
type reportVisualMap struct {
	reportVisualMapDo reportVisualMapDo

	ALL          field.Asterisk
	UUID         field.String // 主键
	CreatorID    field.String // 创建人id
	Creator      field.String // 创建人
	CreateTime   field.Time   // 创建人姓名
	ModifierID   field.String // 修改人id
	Modifier     field.String // 修改人
	ModifyTime   field.Time   // 修改时间
	CreatorOrgID field.Int32  // 创建人组织结构id
	TenantUUID   field.String // 租户UUID
	Name         field.String // 地图名称
	Data         field.String // 地图数据
	Remark       field.String // 备注

	fieldMap map[string]field.Expr
}

func (r reportVisualMap) Table(newTableName string) *reportVisualMap {
	r.reportVisualMapDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r reportVisualMap) As(alias string) *reportVisualMap {
	r.reportVisualMapDo.DO = *(r.reportVisualMapDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *reportVisualMap) updateTableName(table string) *reportVisualMap {
	r.ALL = field.NewAsterisk(table)
	r.UUID = field.NewString(table, "uuid")
	r.CreatorID = field.NewString(table, "creator_id")
	r.Creator = field.NewString(table, "creator")
	r.CreateTime = field.NewTime(table, "create_time")
	r.ModifierID = field.NewString(table, "modifier_id")
	r.Modifier = field.NewString(table, "modifier")
	r.ModifyTime = field.NewTime(table, "modify_time")
	r.CreatorOrgID = field.NewInt32(table, "creator_org_id")
	r.TenantUUID = field.NewString(table, "tenant_uuid")
	r.Name = field.NewString(table, "name")
	r.Data = field.NewString(table, "data")
	r.Remark = field.NewString(table, "remark")

	r.fillFieldMap()

	return r
}

func (r *reportVisualMap) WithContext(ctx context.Context) *reportVisualMapDo {
	return r.reportVisualMapDo.WithContext(ctx)
}

func (r reportVisualMap) TableName() string { return r.reportVisualMapDo.TableName() }

func (r reportVisualMap) Alias() string { return r.reportVisualMapDo.Alias() }

func (r reportVisualMap) Columns(cols ...field.Expr) gen.Columns {
	return r.reportVisualMapDo.Columns(cols...)
}

func (r *reportVisualMap) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *reportVisualMap) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 12)
	r.fieldMap["uuid"] = r.UUID
	r.fieldMap["creator_id"] = r.CreatorID
	r.fieldMap["creator"] = r.Creator
	r.fieldMap["create_time"] = r.CreateTime
	r.fieldMap["modifier_id"] = r.ModifierID
	r.fieldMap["modifier"] = r.Modifier
	r.fieldMap["modify_time"] = r.ModifyTime
	r.fieldMap["creator_org_id"] = r.CreatorOrgID
	r.fieldMap["tenant_uuid"] = r.TenantUUID
	r.fieldMap["name"] = r.Name
	r.fieldMap["data"] = r.Data
	r.fieldMap["remark"] = r.Remark
}

func (r reportVisualMap) clone(db *gorm.DB) reportVisualMap {
	r.reportVisualMapDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r reportVisualMap) replaceDB(db *gorm.DB) reportVisualMap {
	r.reportVisualMapDo.ReplaceDB(db)
	return r
}

type reportVisualMapDo struct{ gen.DO }

func (r reportVisualMapDo) Debug() *reportVisualMapDo {
	return r.withDO(r.DO.Debug())
}

func (r reportVisualMapDo) WithContext(ctx context.Context) *reportVisualMapDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r reportVisualMapDo) ReadDB() *reportVisualMapDo {
	return r.Clauses(dbresolver.Read)
}

func (r reportVisualMapDo) WriteDB() *reportVisualMapDo {
	return r.Clauses(dbresolver.Write)
}

func (r reportVisualMapDo) Session(config *gorm.Session) *reportVisualMapDo {
	return r.withDO(r.DO.Session(config))
}

func (r reportVisualMapDo) Clauses(conds ...clause.Expression) *reportVisualMapDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r reportVisualMapDo) Returning(value interface{}, columns ...string) *reportVisualMapDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r reportVisualMapDo) Not(conds ...gen.Condition) *reportVisualMapDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r reportVisualMapDo) Or(conds ...gen.Condition) *reportVisualMapDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r reportVisualMapDo) Select(conds ...field.Expr) *reportVisualMapDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r reportVisualMapDo) Where(conds ...gen.Condition) *reportVisualMapDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r reportVisualMapDo) Order(conds ...field.Expr) *reportVisualMapDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r reportVisualMapDo) Distinct(cols ...field.Expr) *reportVisualMapDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r reportVisualMapDo) Omit(cols ...field.Expr) *reportVisualMapDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r reportVisualMapDo) Join(table schema.Tabler, on ...field.Expr) *reportVisualMapDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r reportVisualMapDo) LeftJoin(table schema.Tabler, on ...field.Expr) *reportVisualMapDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r reportVisualMapDo) RightJoin(table schema.Tabler, on ...field.Expr) *reportVisualMapDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r reportVisualMapDo) Group(cols ...field.Expr) *reportVisualMapDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r reportVisualMapDo) Having(conds ...gen.Condition) *reportVisualMapDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r reportVisualMapDo) Limit(limit int) *reportVisualMapDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r reportVisualMapDo) Offset(offset int) *reportVisualMapDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r reportVisualMapDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *reportVisualMapDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r reportVisualMapDo) Unscoped() *reportVisualMapDo {
	return r.withDO(r.DO.Unscoped())
}

func (r reportVisualMapDo) Create(values ...*model.ReportVisualMap) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r reportVisualMapDo) CreateInBatches(values []*model.ReportVisualMap, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r reportVisualMapDo) Save(values ...*model.ReportVisualMap) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r reportVisualMapDo) First() (*model.ReportVisualMap, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualMap), nil
	}
}

func (r reportVisualMapDo) Take() (*model.ReportVisualMap, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualMap), nil
	}
}

func (r reportVisualMapDo) Last() (*model.ReportVisualMap, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualMap), nil
	}
}

func (r reportVisualMapDo) Find() ([]*model.ReportVisualMap, error) {
	result, err := r.DO.Find()
	return result.([]*model.ReportVisualMap), err
}

func (r reportVisualMapDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ReportVisualMap, err error) {
	buf := make([]*model.ReportVisualMap, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r reportVisualMapDo) FindInBatches(result *[]*model.ReportVisualMap, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r reportVisualMapDo) Attrs(attrs ...field.AssignExpr) *reportVisualMapDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r reportVisualMapDo) Assign(attrs ...field.AssignExpr) *reportVisualMapDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r reportVisualMapDo) Joins(fields ...field.RelationField) *reportVisualMapDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r reportVisualMapDo) Preload(fields ...field.RelationField) *reportVisualMapDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r reportVisualMapDo) FirstOrInit() (*model.ReportVisualMap, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualMap), nil
	}
}

func (r reportVisualMapDo) FirstOrCreate() (*model.ReportVisualMap, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ReportVisualMap), nil
	}
}

func (r reportVisualMapDo) FindByPage(offset int, limit int) (result []*model.ReportVisualMap, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r reportVisualMapDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r reportVisualMapDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r reportVisualMapDo) Delete(models ...*model.ReportVisualMap) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *reportVisualMapDo) withDO(do gen.Dao) *reportVisualMapDo {
	r.DO = *do.(*gen.DO)
	return r
}
