// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: desc.proto

package server

import (
	"context"

	"ovra/app/system/internal/logic/userrpc"
	"ovra/app/system/internal/svc"
	"ovra/app/system/pb/system"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedUserRpcServer
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRpcServer) Ping(ctx context.Context, in *system.Request) (*system.Response, error) {
	l := userrpclogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
