// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: desc.proto

package server

import (
	"context"

	"ovra/app/monitor/internal/logic/operlogrpc"
	"ovra/app/monitor/internal/svc"
	"ovra/app/monitor/pb/monitor"
)

type OperLogRpcServer struct {
	svcCtx *svc.ServiceContext
	monitor.UnimplementedOperLogRpcServer
}

func NewOperLogRpcServer(svcCtx *svc.ServiceContext) *OperLogRpcServer {
	return &OperLogRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *OperLogRpcServer) Save(ctx context.Context, in *monitor.OperLogReq) (*monitor.EmptyResp, error) {
	l := operlogrpclogic.NewSaveLogic(ctx, s.svcCtx)
	return l.Save(in)
}
